### ISSUE TITLE
Not getting any google drive url

### ISSUE THREAD

**Issue by efikas** [chibikes/share-app-cli#1]
I have followed the installation process and usage, but did not get any google drive link

**Comment by chibikes** [comment]
Were you able to successfully sign in when prompted?

**Comment by efikas** [comment]
It is working now thanks, I didn't authenticate the during the prompt

**Comment by chibikes** [comment]
Okay. That's good to hear. I'll close this. Any other issues you encounter feel free to open an issue and even solve it if you can.
